import {
    CUSTOMIZATION_COLORS_UPDATE, CUSTOMIZATION_LANG_UPDATE, CUSTOMIZATION_LOGO_UPDATE,
    SECURITY_GROUP_CREATE, SECURITY_GROUP_DELETE, SECURITY_GROUP_EDIT, SECURITY_GROUP_SHOW,
    SECURITY_USER_CREATE,
    SECURITY_USER_DELETE,
    SECURITY_USER_EDIT,
    SECURITY_USER_SHOW
} from './permissions'

export const ROLES = {
    ADMIN: {
        NAME: "admin",
        PERMISSIONS: [
            SECURITY_USER_CREATE, SECURITY_USER_EDIT, SECURITY_USER_DELETE, SECURITY_USER_SHOW,
            SECURITY_GROUP_CREATE, SECURITY_GROUP_EDIT, SECURITY_GROUP_DELETE, SECURITY_GROUP_SHOW,
            CUSTOMIZATION_COLORS_UPDATE, CUSTOMIZATION_LOGO_UPDATE, CUSTOMIZATION_LANG_UPDATE
        ]
    },
    OPERATOR: {
        NAME: "operator",
        PERMISSIONS: []
    }
}


export const INIT_USER_ADMIN = {
    username: "root",
    password: "root.123",
    name: "Administrador",
    email: "cristian.cdi@gmail.com",
    phone: "1133126919",
    active: true

}
